server:
  port: 8080
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ztt?serverTimezone=Asia/Shanghai
# mybatis配置
mybatis:
  # 全局mybatis配置
  config-location: classpath:config/mybatis-config.xml
  # mapper的xml文件
  mapper-locations: classpath:mapper/*.xml
